-- --------------------------------------------------------
-- 1. Daily Balances Table
-- Stores the snapshot of the account equity for Risk Management
-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS daily_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE DEFAULT CURRENT_DATE, 
    
    -- Snapshot values
    start_balance NUMERIC NOT NULL,     -- Equity at the beginning of the day (00:00)
    current_balance NUMERIC,            -- Updated on every cycle
    
    -- Metrics
    pnl_daily NUMERIC GENERATED ALWAYS AS (current_balance - start_balance) STORED,
    percent_daily NUMERIC GENERATED ALWAYS AS ((current_balance - start_balance) / NULLIF(start_balance, 0) * 100) STORED,
    
    max_drawdown NUMERIC DEFAULT 0,     -- Max negative % seen today from peak
    peak_balance NUMERIC,               -- Highest balance seen today (for trailing DD)
    
    status TEXT DEFAULT 'ACTIVE',       -- 'ACTIVE', 'STOPPED_RISK' (Loss Limit), 'STOPPED_PROFIT' (Profit Target)
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for quick lookups by status and date
CREATE INDEX IF NOT EXISTS idx_daily_balances_date ON daily_balances(date);

-- --------------------------------------------------------
-- 2. Account Settings (Optional, for persistent Cash tracking)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS account_state (
    id INT PRIMARY KEY DEFAULT 1,
    initial_capital NUMERIC DEFAULT 10000, -- Base capital
    available_cash NUMERIC DEFAULT 10000,  -- Free to trade
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

-- Initial Insert if empty
INSERT INTO account_state (id, initial_capital, available_cash)
SELECT 1, 10000, 10000
WHERE NOT EXISTS (SELECT 1 FROM account_state WHERE id = 1);
